### ISSUE TITLE
De-indent in c++ mode with nested levels

### ISSUE THREAD

**Issue by petercheng00** [Malabarba/aggressive-indent-mode#55]
I've been having issues with my c++ code ending up wrongly indented at the end of files. After some testing I've narrowed it down to the below test case.

First, start with this
```
void a()
{
    {
    }
}

// comment
void b()
{
}
```
Then, add an open brace in a(), which indents everything following it, except for the comment (which is as desired)
```
void a()
{
    {
        {
        }
    }

// comment
    void b()
    {
    }
```
Finally, close the open brace that was added. a() will properly deindent, but b will stay (wrongly) indented
```
void a()
{
    {
        {}
    }
}

// comment
    void b()
    {
    }
```

This issue doesn't happen if a() does not have the extra scope, or if the comment is removed. I presume this has something to do with indent-region-and-on noticing that the comment's indentation doesn't change, but I'm not sure why it only happens for de-indent and why the extra scope matters.

If it matters, I'm using 4 spaces for indentation, with c-default-style set to linux.

**Comment by Malabarba** [comment]
Hey there. This sounds similar to #53 
That one was fixed on the snapshot release, are yoou on the stable releases.

Just in case, I've tagged a new stable release, so you should be able to upgrade in a couple of hours.

**Comment by petercheng00** [comment]
I'm currently up to date on 20150819.313, and still have this issue.

**Comment by Malabarba** [comment]
Ok. Thanks for checking. 

 I'll look into this later, but it's might take a couple of weeks cause things are hectic here right now.

**Comment by petercheng00** [comment]
I realized later that the comment behavior in my example isn't actually what I wanted, as the comment should move with the rest of the code. After disabling a few things, I found linux style to be the culprit.

It looks like with linux style, single line comments that are completely un-indented are regarded as intentional, and thus do not get indented ever. If I understand correctly, when indenting, aggressive indent will happily go past these lines, leaving them un-indented, to continue until the end of the newly-created scope. When de-indenting, aggressive-indent knows to continue past the now-closed scope, until it hits one of the un-touched comment lines, where it has no effect, so it leaves everything afterwards still indented.

One possible way to address this may be to consider traversing until the end of what the scope was, prior to whatever edit was just made - or perhaps add some special-casing though both sound unpleasant to maintain. Fortunately, I'm happy with disabling this comment indentation behavior, so for now I'd consider this as working-as-expected, given the implementation.

**Comment by Malabarba** [comment]
Thanks @petercheng00, your analysis is correct. It might be worth having some special handilng that continues trying to indent if the line that failed was a comment starting at the first column.
I'll create a proper feature request for that, so that I don't forget when I have more time in my hands.
